### ISSUE TITLE
A question about EWC++ implementation

### ISSUE THREAD

**Issue by e0jun** [RaptorMai/online-continual-learning#15]
Hello author,
Thanks for the release of the code of your paper.

After reading your paper and code, I wonder if the best 'lambda' for EWC ++ is 0 when you implemented EWC++ because in your CVPR_config file you said the lambda is 0.

If it is, they are just like fine-tuning?
Thank you :-)

**Comment by czjghost** [comment]
> Hello author, Thanks for the release of the code of your paper.
> 
> After reading your paper and code, I wonder if the best 'lambda' for EWC ++ is 0 when you implemented EWC++ because in your CVPR_config file you said the lambda is 0.
> 
> If it is, they are just like fine-tuning? Thank you :-)

Hello, I suffer same case. I modify lambda to test other case but it does work well than lambda = 0 (indicate it is same as fine-tuning). Maybe it is unsuitable for online class-incremental scenario. This reason I forget what I have seen in other papers. You can try to find the reason from google scholar. ”Regularization Shortcomings for Continual Learning”

**Comment by RaptorMai** [comment]
Hi @e0jun, thank you for your questions and thank @czjghost for your explanation. 

If you read Section 8.2 of my survey paper, you can find a more detailed explanation about this. 

I have also attached a list of papers that I refer to in the survey and you may find them helpful. 

Incdet: In defense of elastic weight consolidation for incremental object detection

Regularization shortcomings for continual learning

Optimal continual learning has perfect memory and is np-hard

Please let me know if you have any other questions.
