### ISSUE TITLE
Implementation error of your code

### ISSUE THREAD

**Issue by chengsilin** [RaptorMai/online-continual-learning#2]
When I tried to run your code, I encountered the following error. Do you know the reason?

-----------run 0-----------avg_end_acc 0.13230000000000003-----------train time 81.69362449645996
/home/slcheng/anaconda3/envs/votenet/lib/python3.7/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims, where=where)
/home/slcheng/anaconda3/envs/votenet/lib/python3.7/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
----------- Total 1 run: 83.46887731552124s -----------
----------- Avg_End_Acc (0.13230000000000003, nan) Avg_End_Fgt (0.14880000000000002, nan) Avg_Acc (0.2081611111111111, nan) Avg_Bwtp (0.0, nan) Avg_Fwt (0.0, nan)-----------

**Comment by RaptorMai** [comment]
Hi, this is not an error but a warning. 

When we calculate the 95% confidence interval, we need to have more than one run. The "nan" means we can't calculate the 95% confidence interval since we only run it once. 

Avg_End_Acc (0.13230000000000003, nan)
