### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by zhangboshi** [RaptorMai/online-continual-learning#5]
![1](https://user-images.githubusercontent.com/59415080/125717547-32a86bf8-c227-43e8-8b96-d8b546589552.png)

Hello scholar, follow the instructions in the readme to run your code, and the above error occurs. What is the reason?

**Comment by irfanfadhullah** [comment]
Hi, I have same error like you, can you share what did you do to solve that kind of problem?

**Comment by zhangboshi** [comment]
i can not solve




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RaptorMai/online-continual-learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 晚上7:55
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [RaptorMai/online-continual-learning] Run error (#5)





 
Hi, I have same error like you, can you share what did you do to solve that kind of problem?
