### ISSUE TITLE
runtime warning

### ISSUE THREAD

**Issue by zhangboshi** [RaptorMai/online-continual-learning#6]
![1](https://user-images.githubusercontent.com/59415080/125717547-32a86bf8-c227-43e8-8b96-d8b546589552.png)

Hello scholar, follow the instructions in the readme to run your code, and the above error occurs. What is the reason?

**Comment by RaptorMai** [comment]
Hi, thank you for your interest in our project. This is not an error but a warning. I have explained this in another issue #2. Please check it out and let me know if you have any other questions.

**Comment by RaptorMai** [comment]
Close for now and please feel free to re-open if you have other questions
