### ISSUE TITLE
Best hyperparameters

### ISSUE THREAD

**Issue by gab709** [RaptorMai/online-continual-learning#7]
Hi, it's possible to have the hyperparameters used for the results reported in the paper "Online Continual Learning in Image Classification: An Empirical Survey"? I'm interested in Core50 results with ICaRL.
Thank you in advance.

**Comment by RaptorMai** [comment]
Hi, thank you so much for your interest in our project. You can find all the hyperparameter information in Appendix B of the paper. I also attached the hyperparameter grid for the compared methods to this post. Please let me know if you have any other questions. 

![image](https://user-images.githubusercontent.com/19519889/128886625-afe39d13-f4db-49ec-b181-68cdaf66a06c.png)

**Comment by gab709** [comment]
> Hi, thank you so much for your interest in our project. You can find all the hyperparameter information in Appendix B of the paper. I also attached the hyperparameter grid for the compared methods to this post. Please let me know if you have any other questions.
> 
> ![image](https://user-images.githubusercontent.com/19519889/128886625-afe39d13-f4db-49ec-b181-68cdaf66a06c.png)

Thank you, the grid is used to tune in the initial phase(2 task for tuning) "to satisfy the requirement that the model does not
see the data of a task more than once", what about the selected hyperparameters for the remaing tasks? Are they available?
Thank you in advance.

**Comment by RaptorMai** [comment]
Hi, the selected hyperparameters are not recorded because we always run the experiments end to end. Depends on the task order, the selected hyperparameters are quite different.

**Comment by gab709** [comment]
Ok, thank you!
